USE Discuss;

CREATE TABLE Topics (
  TopicID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  BoardID INT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(BoardID) REFERENCES Boards(BoardID)
);

CREATE TABLE Posts (
  PostID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TopicID INT NOT NULL,
  FOREIGN KEY(TopicID) REFERENCES Topics(TopicID)
);

CREATE TABLE Users (
  UserID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  UserDisplayName VARCHAR(50) NOT NULL DEFAULT '',
  DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DateDeleted TIMESTAMP,
  DeletedBy INT,
  FOREIGN KEY(DeletedBy) REFERENCES Users(UserID)
);

USE Discuss;
CREATE TABLE PostsVersions (
  PostID INT NOT NULL,
  Version INT NOT NULL,
  AuthorID INT NOT NULL,
  DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PostContent TEXT NOT NULL,
  DateDeleted TIMESTAMP,
  DeletedBy INT,
  PRIMARY KEY(PostID, Version),
  FOREIGN KEY(DeletedBy) REFERENCES Users(UserID),
  FOREIGN KEY(PostID) REFERENCES Posts(PostID),
  FOREIGN KEY(AuthorID) REFERENCES Users(UserID)
);

CREATE TRIGGER PostsVersions_Increment_Version
  BEFORE INSERT
  ON PostsVersions
  FOR EACH ROW
BEGIN
    SET @id1 = NULL;

    IF NEW.Version = -1 THEN
      SELECT COALESCE(MAX(Version) + 1, 1) INTO @id1 FROM PostsVersions WHERE PostsVersions.PostID = NEW.PostID;
      SET NEW.Version = @id1;
    END IF;
END